spring:
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/static/
    suffix: .html
  jpa:
    database: mysql
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hibernate
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties
netease:
  public:
    appKey: 953690a751e101eca530ab3d5bb48d99
    appSecret: f3acbec91bf5
logging:
  level:
    root: debug
server:
  port: 8443
  ssl:
    key-store: tomcat.keystore
    key-alias: tomcat
    key-store-password: mingxiangjun
    key-store-type: JKS
  servlet:
    context-path: /
