server:
  port: 80
  servlet:
    context-path: /
spring:
  jpa:
    database: mysql
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hibernate
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
logging:
  level:
    root: debug
